---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes 1;
    # daemon off;
    
    events {
        worker_connections 2048;
    }
    
    http {
      server {
        listen 8080;
    
        location / {
          proxy_pass http://127.0.0.1:8000/;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Prefix /;
        }
      }
    }
