---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes 1;
    # daemon off;
    error_log /dev/stdout info;
    
    events {
        worker_connections 2048;
    }
    
    http {

      upstream app_servers {
          server 127.0.0.1:8000;
      }

      server {
        listen 8080;
    
        location / {
          proxy_pass http://app_servers;
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
          client_body_buffer_size 20m;
        }
      }
    }
