---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes 1;
    # daemon off;
    error_log /dev/stdout info;
    
    events {
        worker_connections 2048;
    }
    
    http {

      upstream app_servers {
          server 127.0.0.1:8000;
      }

      server {
        listen 8080;
    
        location / {
          proxy_pass http://app_servers;
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;

          client_max_body_size    20M;
          client_body_buffer_size 20M;
          proxy_buffers           32 4k;
          proxy_connect_timeout   90;
          proxy_send_timeout      90;
          proxy_read_timeout      90;
        }
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: backend-conf
data:
  production.py: |
    from .base import *
    
    DEBUG = False
    
    try:
        from .local import *
    except ImportError:
        pass
    
    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = "agl67OI8O4Nf5BwZK0xpBbbAokTuqppLz99JfDhT-pu6MfNmodtsYNa-vS7kwY-wcC-Ntd3ydJKpRMPvqukCYm9tEnj9XMQB"
    
    # https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
    # django < 4.2
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # AWS Settings
    # https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
    AWS_S3_REGION_NAME = "fr-par"
    AWS_S3_ACCESS_KEY_ID = "SCWQKMT1BTWKE4FYC137"
    AWS_S3_SECRET_ACCESS_KEY = "d3ecacea-35f8-46f4-ba89-66e4ac30253e"
    AWS_STORAGE_BUCKET_NAME = "hydrocamp"
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_ENDPOINT_URL = 'https://hydrocamp.s3.fr-par.scw.cloud'
    
    # s3 static settings
    AWS_LOCATION = 'static'
    STATIC_URL = f'https://hydrocamp.s3.fr-par.scw.cloud/{AWS_LOCATION}/'
    # django < 4.2
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
    
    # SECURITY WARNING: define the correct hosts in production!
    ALLOWED_HOSTS = ["*"]

    #
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": "postgresql.postgresql.svc.cluster.local",
            "NAME": "hydrocamp",
            "USER": "hydrocamp",
            "PASSWORD": "fz7koVwJiswdD6jNnPCM",
        }
    }
